apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-auto-sync-diff
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    path: guestbook
    repoURL: https://github.com/Samba73/argocd-example-apps.git
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Replace=true
    automated:
      selfHeal: true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
      - /spc/replicas 
 
