apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-p
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook-p
  source:
    path: guestbook
    repoURL: https://github.com/Samba73/argocd-example-apps.git
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
