apiVersion: v1
kind: Secret
metadata:
  name: private-repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/Samba73/argo-example-private.git
  password: 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
  username: test

  
