apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: demo2-project
  namespace: argocd
spec:
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: 'ns-1'
    server: '*'
  sourceRepos:
  - '*'
