apiVersion: batch/v1
kind: Job
metadata:
  generateName: pre-run-
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: pre
        image: alpine
        command: ["sleep",  "10"]
      restartPolicy: Never
  backoffLimit: 0
---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: main
  annotations:
    argocd.argoproj.io/hook: Sync
spec:
  template:
    spec:
      containers:
      - name: main
        image: alpine
        command: ["sleep",  "10"]
      restartPolicy: Never
  backoffLimit: 0
---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: pre-run-post-run-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookFailed
spec:
  template:
    spec:
      containers:
      - name: post
        image: alpine
        command: ["sleep",  "10"]
      restartPolicy: Never
  backoffLimit: 0
---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: skip-
  annotations:
    argocd.argoproj.io/hook: Skip
spec:
  template:
    spec:
      containers:
      - name: skip
        image: alpine
        command: ["sleep",  "10"]
      restartPolicy: Never
  backoffLimit: 0
