apiVersion: batch/v1
kind: Job
metadata:
   generateName: pre-1-
   annotations:
     argocd.argoproj.io/hook: PreSync
     argocd.argoproj.io/sync-wave: "0"
spec:
  template:
    spec:
       containers:
       - name: pre
         image: alpine
         command: ["sleep", "10"] 
       restartPolicy: Never  
---
apiVersion: batch/v1
kind: Job
metadata:
   generateName: pre-2-
   annotations:
     argocd.argoproj.io/hook: PreSync
     argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    spec:
       containers:
       - name: pre
         image: alpine
         command: ["sleep", "10"]
       restartPolicy: Never    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: service-backend
spec:
  selector:
    app: myapp
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: maintpage-up-
  annotations:
     argocd.argoproj.io/hook: Sync
     argocd.argoproj.io/sync-wave: "1"
     argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: maintpage-up
        image: alpine
        command: ["sleep",  "10"]
      restartPolicy: Never
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-frontend
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: service-frontend
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    app: myapp
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: maintpage-down-
  annotations:
     argocd.argoproj.io/hook: Sync
     argocd.argoproj.io/sync-wave: "3"
     argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: maintpage-down
        image: alpine
        command: ["sleep",  "10"]
      restartPolicy: Never



 
